re_add_city = {'陇南': 'longnan', '儋州': 'danzhou', '吴忠': 'wuzhong', '宁德': 'ningde', '文山州': 'wenshan', '盐城': 'yancheng',
               '眉山': 'meishan', '黑河': 'heihe', '阿拉尔': 'alaer', '钦州': 'qinzhou', '安阳': 'anyang', '商洛': 'shangluo',
               '重庆': 'chongqing', '临沧': 'linchang', '普洱': 'puer', '云浮': 'yunfu', '中卫': 'zhongwei', '聊城': 'liaocheng',
               '安顺': 'anshun', '枣庄': 'zaozhuang', '乌兰察布': 'wulanchabu', '乐东': 'ledong', '长治': 'changzhi',
               '新乡': 'xinxiang', '丹东': 'dandong', '防城港': 'fangchenggang', '六盘水': 'liupanshui', '泰安': 'taian',
               '鸡西': 'jixi', '龙岩': 'longyan', '日喀则': 'rikazediqu', '汉中': 'hanzhong', '漳州': 'zhangzhou', '大庆': 'daqing',
               '商丘': 'shangqiu', '咸阳': 'xianyang', '昆明': 'kunming', '潮州': 'chaozhou', '芜湖': 'wuhu', '伊犁': 'yili',
               '三沙': 'sansha', '丽江': 'lijiang', '文昌': 'wenchang', '双鸭山': 'shuangyashan', '保山': 'baoshan',
               '天津': 'tianjin', '金昌': 'jinchang', '白城': 'baicheng', '宜昌': 'yichang', '白山': 'baishan', '德阳': 'deyang',
               '厦门': 'xiamen', '宣城': 'xuancheng', '牡丹江': 'mudanjiang', '呼和浩特': 'huhehaote', '黄冈': 'huanggang',
               '恩施': 'enshizhou', '肇庆': 'zhaoqing', '宿州': 'anhuisuzhou', '柳州': 'liuzhou', '五指山': 'wuzhishan',
               '锦州': 'jinzhou', '潍坊': 'weifang', '承德': 'chengde', '徐州': 'xuzhou', '桂林': 'guilin', '曲靖': 'qujing',
               '滨州': 'binzhou', '玉林': 'guangxiyulin', '南平': 'nanping', '安庆': 'anqing', '晋城': 'jincheng', '鄂州': 'ezhou',
               '南通': 'nantong', '六安': 'liuan', '忻州': 'xinzhou', '鹤壁': 'hebi', '盘锦': 'panjin', '揭阳': 'jieyang',
               '张家口': 'zhangjiakou', '雅安': 'yaan', '天水': 'tianshui', '武威': 'wuwei', '台州': 'zhejiangtaizhou',
               '琼中': 'qiongzhong', '中山': 'zhongshan', '延安': 'yanan', '连云港': 'lianyuangang', '北屯': 'beitun',
               '济宁': 'jining', '琼海': 'qionghai', '景德镇': 'jingdezhen', '吕梁': 'lvliang', '平顶山': 'pingdingshan',
               '抚州': 'jiangxifuzhou', '梅州': 'meizhou', '蚌埠': 'bengbu', '吉林': 'jilin', '赣州': 'ganzhou',
               '长春': 'changchun', '嘉峪关': 'jiayuguan', '张家界': 'zhangjiajie', '金华': 'jinhua', '银川': 'yinchuan',
               '朔州': 'shuozhou', '赤峰': 'chifeng', '沈阳': 'shenyang', '保定': 'baoding', '阳江': 'yangjiang',
               '扬州': 'yangzhou', '佳木斯': 'jiamusi', '安康': 'ankang', '济源': 'jiyuan', '益阳': 'yiyang', '博尔塔拉': 'boertala',
               '仙桃': 'xiantao', '阿里': 'ali', '岳阳': 'yueyang', '包头': 'baotou', '汕头': 'shantou', '信阳': 'xinyang',
               '通化': 'tonghua', '长沙': 'changsha', '七台河': 'qitaihe', '山南': 'shannan', '江门': 'jiangmen', '兰州': 'lanzhou',
               '乐山': 'leshan', '太原': 'taiyuan', '深圳': 'shenzhen', '大兴安岭': 'daxinganling', '海东': 'haidong',
               '广安': 'guangan', '来宾': 'laibin', '绍兴': 'shaoxing', '南阳': 'nanyang', '镇江': 'zhenjiang', '四平': 'siping',
               '遂宁': 'suining', '南宁': 'nanning', '株洲': 'zhuzhou', '昭通': 'zhaotong', '淄博': 'zibo', '焦作': 'jiaozuo',
               '德州': 'dezhou', '娄底': 'loudi', '武汉': 'wuhan', '黄石': 'huangshi', '营口': 'yingkou', '崇左': 'chongzuo',
               '大同': 'datong', '宜春': 'jiangxiyichun', '榆林': 'yulin', '池州': 'chizhou', '昌江': 'changjiang',
               '贵阳': 'guiyang', '抚顺': 'fushun', '广州': 'guangzhou', '周口': 'zhoukou', '石嘴山': 'shizuishan',
               '延边': 'yanbian', '荆州': 'jingzhou', '绵阳': 'mianyang', '阜新': 'fuxin', '洛阳': 'luoyang', '丽水': 'lishui',
               '珠海': 'zhuhai', '苏州': 'suzhou', '黔南': 'qiannan', '郴州': 'chenzhou', '新余': 'xinyu', '湛江': 'zhanjiang',
               '资阳': 'ziyang', '南昌': 'nanchang', '石河子': 'shihezi', '泸州': 'luzhou', '莱芜': 'laiwu', '玉溪': 'yuxi',
               '九江': 'jiujiang', '河源': 'heyuan', '三门峡': 'sanmenxia', '湖州': 'huzhou', '铜川': 'tongchuan', '固原': 'guyuan',
               '淮安': 'huaian', '鄂尔多斯': 'eerduosi', '白银': 'baiyin', '朝阳': 'chaoyang', '百色': 'baise', '无锡': 'wuxi',
               '葫芦岛': 'huludao', '梧州': 'wuzhou', '巴中': 'bazhong', '陵水': 'lingshui', '衡水': 'hengshui', '常德': 'changde',
               '襄阳': 'xiangyang', '宿迁': 'suqian', '河池': 'hechi', '淮北': 'huaibei', '铜仁': 'tongrendiqu', '自贡': 'zigong',
               '湘西': 'xiangxi', '保亭': 'baoting', '西宁': 'xining', '白沙': 'baisha', '三亚': 'sanya', '咸宁': 'xianning',
               '滁州': 'chuzhou', '海口': 'haikou', '黔西南': 'qianxinan', '临汾': 'linfen', '泉州': 'quanzhou', '红河': 'honghe',
               '马鞍山': 'maanshan', '北京': 'beijing', '宝鸡': 'baoji', '孝感': 'xiaogan', '济南': 'jinan', '郑州': 'zhengzhou',
               '内江': 'neijiang', '贵港': 'guigang', '淮南': 'huainan', '惠州': 'huizhou', '张掖': 'zhangye', '衢州': 'quzhou',
               '鹰潭': 'yingtan', '通辽': 'tongliao', '图木舒克': 'tumushuke', '攀枝花': 'panzhihua', '濮阳': 'puyang',
               '运城': 'yuncheng', '永州': 'yongzhou', '达州': 'dazhou', '邵阳': 'shaoyang', '嘉兴': 'jiaxing', '菏泽': 'heze',
               '阜阳': 'fuyang', '温州': 'wenzhou', '遵义': 'zunyi', '铜陵': 'tongling', '五家渠': 'wujiaqu', '唐山': 'tangshan',
               '酒泉': 'jiuquan', '海南州': 'hainanzhou', '烟台': 'yantai', '合肥': 'hefei', '巴彦淖尔': 'bayannaoer',
               '成都': 'chengdu', '广元': 'guangyuan', '泰州': 'taizhou', '邯郸': 'handan', '荆门': 'jinmen', '怀化': 'huaihua',
               '漯河': 'luohe', '伊春': 'yichun', '萍乡': 'pingxiang', '南京': 'nanjing', '哈尔滨': 'haerbin', '莆田': 'putian',
               '宁波': 'ningbo', '拉萨': 'lasa', '乌鲁木齐': 'wulumuqi', '十堰': 'shiyan', '舟山': 'zhoushan', '那曲': 'naqu',
               '铁岭': 'tieling', '驻马店': 'zhumadian', '秦皇岛': 'qinhuangdao', '乌海': 'wuhai', '黔东南': 'qiandongnan',
               '克拉玛依': 'kelamayi', '三明': 'sanming', '上海': 'shanghai', '甘南': 'gannanzhou', '东莞': 'dongguan',
               '绥化': 'suihua', '辽源': 'liaoyuan', '茂名': 'maoming', '亳州': 'bozhou', '上饶': 'shangrao', '西安': 'xian',
               '东方': 'dongfang', '威海': 'weihai', '青岛': 'qingdao', '阳泉': 'yangquan', '潜江': 'qianjiang', '大连': 'dalian',
               '贺州': 'hezhou', '甘孜州': 'ganzi', '衡阳': 'hengyang', '宜宾': 'yibin', '韶关': 'shaoguan',
               '巴音郭楞': 'bayinguoleng', '邢台': 'xingtai', '南充': 'nanchong', '沧州': 'cangzhou', '万宁': 'wanning',
               '庆阳': 'qingyang', '呼伦贝尔': 'hulunbeier', '渭南': 'weinan', '佛山': 'foshan', '廊坊': 'langfang',
               '杭州': 'hangzhou', '石家庄': 'shijiazhuang', '天门': 'tianmen', '东营': 'dongying', '辽阳': 'liaoyang',
               '许昌': 'xuchang', '定西': 'dingxi', '平凉': 'pingliang', '鞍山': 'anshan', '松原': 'songyuan', '黄山': 'huangshan',
               '鹤岗': 'hegang', '开封': 'kaifeng', '日照': 'rizhao', '湘潭': 'xiangtan', '北海': 'beihai', '晋中': 'jinzhong',
               '齐齐哈尔': 'qiqihaer', '临沂': 'linyi', '克孜勒苏': 'kezilesu', '随州': 'suizhou', '汕尾': 'shanwei', '福州': 'fuzhou',
               '本溪': 'benxi', '清远': 'qingyuan', '常州': 'changzhou', '吉安': 'jian', '锡林郭勒盟': 'xilinguole', '阿坝州': 'aba',
               '临夏': 'linxiazhou', '毕节': 'bijieshi', '林芝': 'linzhi', '临高': 'lingao', '迪庆州': 'diqing', '大理': 'dali',
               '哈密': 'hamidiqu', '和田': 'hetiandiqu', '凉山州': 'liangshan', '玉树州': 'yushu', '屯昌': 'tunchang',
               '定安': 'dingan', '阿克苏': 'akesudiqu', '海北州': 'haibei', '吐鲁番': 'tulufandiqu', '神农架': 'shennongjia',
               '塔城': 'tachengdiqu', '阿勒泰': 'aletaidiqu', '德宏州': 'dehong', '果洛州': 'guoluo', '楚雄': 'chuxiongzhou',
               '昌都': 'changdudiqu', '喀什': 'kashidiqu', '怒江州': 'nujiang', '黄南州': 'huangnan', '昌吉': 'changjizhou',
               '海西州': 'haixi', '澄迈': 'chengmai', '西双版纳州': 'xishuangbanna', '铁门关': 'tiemenguan', }
city_dict = {
    '深圳': 'shenzhen', '阳江': 'yangjiang', '曲靖': 'qujing', '乐山': 'leshan',
}
